### ISSUE TITLE
bug - click task list, the system crashed

### ISSUE THREAD

**Issue by lxm218** [lxm218/google_form_addon#1]
info: Fri, 28 Jul 2017 21:59:46 GMT actions-on-google:debug getContextArgument: contextName=actions_intent_option, argName=OPTION
info: Fri, 28 Jul 2017 21:59:46 GMT actions-on-google:debug getContextArgument: contextName=actions_intent_option, argName=OPTION
Fri, 28 Jul 2017 21:59:46 GMT actions-on-google:debug getContextArgument: contextName=actions_intent_option, argName=OPTION
****************************USER SELECTED: 20ffe30d838
Survey starting....
error: (node:2872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError:Cannot read property 'items' of null

**Comment by kevingzhang** [comment]
fixed and committed , please test
